// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: bird-test1

#ifndef _BIRD_TEST1_UI_H
#define _BIRD_TEST1_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_cone
void ui_cone_screen_init(void);
extern lv_obj_t * ui_cone;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_valc;
extern lv_obj_t * ui_elsc;
extern lv_obj_t * ui_tempc;
extern lv_obj_t * ui_temp;
extern lv_obj_t * ui_val;
extern lv_obj_t * ui_ele;
extern lv_obj_t * ui_start;
extern lv_obj_t * ui_bat;
extern lv_obj_t * ui____initial_actions0;








void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
